-- MySQL Script generated by MySQL Workbench
-- Wed Sep 17 19:16:46 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Provincia` (
  `idProvincia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idProvincia`),
  UNIQUE INDEX `idProvincia_UNIQUE` (`idProvincia` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Localidad` (
  `idLocalidad` INT NOT NULL AUTO_INCREMENT,
  `codPostal` INT NULL,
  `nombre` VARCHAR(45) NULL,
  `idProvincia` INT NOT NULL,
  PRIMARY KEY (`idLocalidad`),
  UNIQUE INDEX `idLocalidad_UNIQUE` (`idLocalidad` ASC) VISIBLE,
  INDEX `fk_Localidad_Provincia1_idx` (`idProvincia` ASC) VISIBLE,
  CONSTRAINT `fk_Localidad_Provincia1`
    FOREIGN KEY (`idProvincia`)
    REFERENCES `mydb`.`Provincia` (`idProvincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `cuit` bigint NOT NULL,
  `telefono` INT(30) NULL,
  PRIMARY KEY (`idPersona`),
  UNIQUE INDEX `idPersona_UNIQUE` (`idPersona` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(45) NULL,
  `observaciones` VARCHAR(45) NULL,
  `razonSocial` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `idPersona` INT NOT NULL, -- VUELVO A PONERLO EN NOT NULL
  `idLocalidad` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `idCliente_UNIQUE` (`idCliente` ASC) VISIBLE,
  INDEX `fk_Cliente_Persona1_idx` (`idPersona` ASC) VISIBLE,
  INDEX `fk_Cliente_Localidad1_idx` (`idLocalidad` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE CASCADE  -- SI BORRA UNA PERSONA SE BORRA TAMBIEN SU OBJETO CLIENTE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Cliente_Localidad1`
    FOREIGN KEY (`idLocalidad`)
    REFERENCES `mydb`.`Localidad` (`idLocalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Chofer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Chofer` (
  `idChofer` INT NOT NULL AUTO_INCREMENT,
  `dni` INT NULL,
  `estadoDisponibilidad` ENUM('Libre','Ocupado','Inhabilitado') NOT NULL,
  `idPersona` INT NOT NULL,
  PRIMARY KEY (`idChofer`),
  UNIQUE INDEX `idChofer_UNIQUE` (`idChofer` ASC) VISIBLE,
  INDEX `fk_Chofer_Persona1_idx` (`idPersona` ASC) VISIBLE,
  CONSTRAINT `fk_Chofer_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE CASCADE -- SI BORRA UNA PERSONA SE BORRA TAMBIEN SU OBJETO CHOFER
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vehiculo` (
  `idVehiculo` INT NOT NULL AUTO_INCREMENT,
  `anio` INT NULL,
  `estado` VARCHAR(45) NULL,
  `marca` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `patente` VARCHAR(10) NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idVehiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ChoferXVehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ChoferXVehiculo` (
  `idChoferVehiculo` INT NOT NULL AUTO_INCREMENT,
  `idChofer` INT NOT NULL,
  `idVehiculo` INT NOT NULL,
  `fechaAsignacion` DATE NOT NULL,  
  PRIMARY KEY (`idChoferVehiculo`),
  INDEX `fk_ChoferXVehiculo_Chofer1_idx` (`idChofer` ASC) VISIBLE,
  INDEX `fk_ChoferXVehiculo_Vehiculo1_idx` (`idVehiculo` ASC) VISIBLE,
  UNIQUE INDEX `uq_chofer_vehiculo` (`idChofer` ASC, `idVehiculo` ASC) VISIBLE,
  CONSTRAINT `fk_ChoferXVehiculo_Chofer1`
    FOREIGN KEY (`idChofer`)
    REFERENCES `mydb`.`Chofer` (`idChofer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ChoferXVehiculo_Vehiculo1`
    FOREIGN KEY (`idVehiculo`)
    REFERENCES `mydb`.`Vehiculo` (`idVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Viaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Viaje` (
  `idViaje` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `kilometros` FLOAT NULL,
  `observaciones` VARCHAR(45) NULL,
  `motivoCancelacion` VARCHAR(45) NULL,
  `precio` FLOAT NULL,
  `idCliente` INT NOT NULL,
  `idLocalidadOrigen` INT NOT NULL,
  `idLocalidadDestino` INT NOT NULL,
  `idChofer` INT NOT NULL,
  `idVehiculo` INT NOT NULL,
  PRIMARY KEY (`idViaje`),
  INDEX `fk_Viaje_Cliente1_idx` (`idCliente` ASC) VISIBLE,
  UNIQUE INDEX `idViaje_UNIQUE` (`idViaje` ASC) VISIBLE,
  INDEX `fk_Viaje_Localidad2_idx` (`idLocalidadOrigen` ASC) VISIBLE,
  INDEX `fk_Viaje_Localidad1_idx` (`idLocalidadDestino` ASC) VISIBLE,
  INDEX `fk_Viaje_Chofer1_idx` (`idChofer` ASC) VISIBLE,
  INDEX `fk_Viaje_Vehiculo1_idx` (`idVehiculo` ASC) VISIBLE,
  CONSTRAINT `fk_Viaje_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Viaje_Localidad2`
    FOREIGN KEY (`idLocalidadOrigen`)
    REFERENCES `mydb`.`Localidad` (`idLocalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Viaje_Localidad1`
    FOREIGN KEY (`idLocalidadDestino`)
    REFERENCES `mydb`.`Localidad` (`idLocalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Viaje_Chofer1`
    FOREIGN KEY (`idChofer`)
    REFERENCES `mydb`.`ChoferXVehiculo` (`idChofer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_Viaje_Vehiculo1`
    FOREIGN KEY (`idVehiculo`)
    REFERENCES `mydb`.`ChoferXVehiculo` (`idVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Gasto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gasto` (
  `idGasto` INT NOT NULL AUTO_INCREMENT,
  `detalle` VARCHAR(255) NULL,
  `monto` FLOAT NULL,
  `tipo` VARCHAR(45) NULL,
  `idViaje` INT NOT NULL,
  PRIMARY KEY (`idGasto`, `idViaje`),
  UNIQUE INDEX `idGasto_UNIQUE` (`idGasto` ASC) VISIBLE,
  INDEX `fk_Gasto_Viaje1_idx` (`idViaje` ASC) VISIBLE,
  CONSTRAINT `fk_Gasto_Viaje1`
    FOREIGN KEY (`idViaje`)
    REFERENCES `mydb`.`Viaje` (`idViaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Documentacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Documentacion` (
  `idDocumentacion` INT NOT NULL AUTO_INCREMENT,
  `detalle` VARCHAR(100) NULL,
  `estado` ENUM('Vigente','Vencida') NULL,
  `nombre` VARCHAR(45) NULL,
  `renovacion` INT NULL,
  `fechaVencimiento` DATE NULL,
  `idVehiculo` INT NULL,
  `idChofer` INT NULL,
  PRIMARY KEY (`idDocumentacion`),
  INDEX `fk_Documentacion_Vehiculo1_idx` (`idVehiculo` ASC) VISIBLE,
  INDEX `fk_Documentacion_Chofer1_idx` (`idChofer` ASC) VISIBLE,
  CONSTRAINT `fk_Documentacion_Vehiculo1`
    FOREIGN KEY (`idVehiculo`)
    REFERENCES `mydb`.`Vehiculo` (`idVehiculo`) -- SI BORRA UN VEHICULO SE BORRA TAMBIEN SU DOCUMENTACION
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Documentacion_Chofer1`
    FOREIGN KEY (`idChofer`)
    REFERENCES `mydb`.`Chofer` (`idChofer`) -- SI BORRA UN CHOFER SE BORRA TAMBIEN SU DOCUMENTACION
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `contraseña` VARCHAR(45) NULL,
  `nombreUsuario` VARCHAR(45) NULL,
  `rol` VARCHAR(45) NULL,
  `idPersona` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_Usuario_Persona1_idx` (`idPersona` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mantenimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mantenimiento` (
  `idMantenimiento` INT NOT NULL AUTO_INCREMENT, -- ¡Agregado AUTO_INCREMENT!
  `fecha` DATE NULL,
  `observaciones` VARCHAR(255) NULL, -- Más espacio para observaciones
  `tipo` VARCHAR(45) NULL,
  `idVehiculo` INT NOT NULL,
  PRIMARY KEY (`idMantenimiento`),
  INDEX `fk_Mantenimiento_Vehiculo1_idx` (`idVehiculo` ASC) VISIBLE,
  CONSTRAINT `fk_Mantenimiento_Vehiculo1`
    FOREIGN KEY (`idVehiculo`)
    REFERENCES `mydb`.`Vehiculo` (`idVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
